from . import hr_employee
from . import res_partner
from . import res_partner_nationality
from . import project_task
from . import project_project
from . import account_move
from . import dafo
from . import incidence_line_data
from . import incidence_data
from . import social_report
from . import pai
